# Generated by Django 4.2.21 on 2025-09-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_create_collections_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestrabiologica',
            name='datos_morfologicos',
            field=models.TextField(blank=True, help_text='Altura, tipo de hojas, color de flores/frutos', null=True),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='epoca_floracion',
            field=models.CharField(blank=True, help_text='Meses o temporada de floración', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='epoca_fructificacion',
            field=models.CharField(blank=True, help_text='Meses o temporada de fructificación', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='habitat',
            field=models.CharField(blank=True, help_text='Tipo de ecosistema (bosque, selva, etc.)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='usos_tradicionales',
            field=models.TextField(blank=True, help_text='Medicinales, culinarios, ornamentales, rituales', null=True),
        ),
    ]
